version: '3.5'
services:
  # Nginx反向代理服务
  go-emby2alist:
    image: crpi-zutrieltt9z6q9p7.cn-shanghai.personal.cr.aliyuncs.com/awordx/go-emby2alist:latest
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    container_name: go-emby2alist
    volumes:
      - /volume1/docker/alist_rename/config/config.yml:/app/config.yml
    ports:
      - 8895:8095 # http
      - 8894:8094 # https

  # Alist文件重命名服务
  alist-rename:
    image: crpi-zutrieltt9z6q9p7.cn-shanghai.personal.cr.aliyuncs.com/awordx/alist-renmae-strm:latest
    container_name: alist-rename
    ports:
      - "5050:5050"   # API服务端口
    volumes:
      - /volume1/docker/alist_rename/data:/usr/local/data
      - /volume1/docker/alist_rename/config:/usr/local/config
      - /volume3/影视资源/alist_strm:/alist_strm
    environment:
      - restart_update=False
#      - use_thire_rename=True
    restart: always

