[alistconfig]
alist_url = 你的alist地址，例如：http://ip:5244
alist_apikey = alist地址的apitoken，例如alist-*****
alist_password = alist账户的密码
#程序执行第一次进行刷新的文件夹
#以下的路径都是alist的路径，例如/115这个路径，在alist里面网址里显示是http://ip:5244/115
refresh_folder = 一个挂载在alist的网盘路径，例如 /115
#需要监控的alist文件夹，程序暂时支持三个文件夹，且不能更改
sync_movie_new = 监控的电影文件夹，例如：sync_movie_new = /115/电影，不需要引号
sync_anime_new = 监控的电影文件夹，例如/115/动漫
sync_series = 监控的剧集文件夹，例如/115/剧集

[emby_config]
emby_url = 你的emby地址，例如http://ip:端口
library_anime_new = 挂载/115/动漫 的strm文件夹的媒体库名字，例如：115动漫
library_movie_new = 挂载/115/电影 的strm文件夹的媒体库名字，例如：115电影
library_series = 挂载/115/电影 的strm文件夹的媒体库名字，例如：115剧集
api_key = 在emby里面生成一个apitoken，例如：121942****************
iyuu_token = emby刷新后会向手机推送提醒，即爱与飞飞的令牌，例如：IYUU*********

[user_config]
#这两项，默认就行不需要修改
scripts_path = /usr/local/alist_rename.py
flask_port = 5050


[paths]#nas相关的配置路径
#如果用得着就修改，用不着默认就行
to_named_path = /115/剧集
#这个是strm存放的根目录，比如说你的电影在alist里面的路径是/115/电影/天空之城，那么生成的strm所在的目录就是
#/本地目录+/115/电影/天空之城 = /本地目录/115/电影/天空之城
local_strm_root_path = /alist_strm


